# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 246e091a9d5b15fdf2de941d8b2460bbfb39036e7b01627bbfb04d078e395f4f4ebc7153f05f420673cba5a757ae7eca48a26bc7ae0eb516014003c8218343e9

test:
  secret_key_base: 5c5b7925e428122b8aa013fb511f91665e40b73cdaf3f11c09e4e214dd7311f6d4699ffd79e858c36d5541cc0d65aa5069df1df1f0696e2d37a05cd822d496ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
